In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [9]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

c:\Users\rashi_\OneDrive\Desktop\DEEP_LEARNING_NLP\venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [14]:
## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [16]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [17]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 100916.2422 - mae: 100916.2422 - val_loss: 98554.9688 - val_mae: 98554.9688
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 100394.9219 - mae: 100394.9219 - val_loss: 97327.4453 - val_mae: 97327.4453
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 98575.5234 - mae: 98575.5234 - val_loss: 94172.1953 - val_mae: 94172.1953
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 93785.2031 - mae: 93785.2031 - val_loss: 88795.5781 - val_mae: 88795.5781
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 88376.8047 - mae: 88376.8047 - val_loss: 81612.2969 - val_mae: 81612.2969
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 81440.2422 - mae: 81440.2422 - val_loss: 73569.8672 - val_mae: 73569.8672
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 73116.1328 - mae: 73116.1328 - val_loss: 65900.0938 - val_mae: 65900.0938
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 65146.9883 - mae: 65146.9883 - val_loss: 59559.3281 - val_mae: 59559.3281
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 59222.0039 - mae: 59222.0039 - val_loss: 55109.6055 - val_mae: 55109.6055
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53833.5859 - mae: 53833.5859 - val_loss: 52587.2930 - val_mae: 52587.2930
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52097.1289 - mae: 52097.1289 - val_loss: 51517.5859 - val_mae: 51517.5859
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51025.0742 - mae: 51025.0742 - val_loss: 51132.1875 - val_mae: 51132.1875
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51152.6406 - mae: 51152.6406 - val_loss: 50992.9766 - val_mae: 50992.9766
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50776.4766 - mae: 50776.4766 - val_loss: 50923.6836 - val_mae: 50923.6836
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50330.3086 - mae: 50330.3086 - val_loss: 50865.5234 - val_mae: 50865.5234
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50095.9180 - mae: 50095.9180 - val_loss: 50817.8203 - val_mae: 50817.8203
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50298.5938 - mae: 50298.5938 - val_loss: 50767.0742 - val_mae: 50767.0742
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49698.7383 - mae: 49698.7383 - val_loss: 50728.7070 - val_mae: 50728.7070
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49865.2930 - mae: 49865.2930 - val_loss: 50683.8516 - val_mae: 50683.8516
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50268.6016 - mae: 50268.6016 - val_loss: 50650.2852 - val_mae: 50650.2852
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49928.0586 - mae: 49928.0586 - val_loss: 50615.0078 - val_mae: 50615.0078
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49578.4023 - mae: 49578.4023 - val_loss: 50591.4609 - val_mae: 50591.4609
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50200.8594 - mae: 50200.8594 - val_loss: 50573.3438 - val_mae: 50573.3438
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49533.5508 - mae: 49533.5508 - val_loss: 50544.7539 - val_mae: 50544.7539
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49728.3164 - mae: 49728.3164 - val_loss: 50527.4336 - val_mae: 50527.4336
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50457.1250 - mae: 50457.1250 - val_loss: 50517.4258 - val_mae: 50517.4258
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49813.8438 - mae: 49813.8438 - val_loss: 50500.4258 - val_mae: 50500.4258
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49943.0859 - mae: 49943.0859 - val_loss: 50484.7227 - val_mae: 50484.7227
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49752.2188 - mae: 49752.2188 - val_loss: 50472.3828 - val_mae: 50472.3828
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49889.0898 - mae: 49889.0898 - val_loss: 50451.3750 - val_mae: 50451.3750
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49881.5664 - mae: 49881.5664 - val_loss: 50436.4023 - val_mae: 50436.4023
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49371.4531 - mae: 49371.4531 - val_loss: 50415.2891 - val_mae: 50415.2891
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50042.6133 - mae: 50042.6133 - val_loss: 50403.7773 - val_mae: 50403.7773
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49964.5078 - mae: 49964.5078 - val_loss: 50388.5352 - val_mae: 50388.5352
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49676.2852 - mae: 49676.2852 - val_loss: 50376.4570 - val_mae: 50376.4570
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49716.5625 - mae: 49716.5625 - val_loss: 50375.7148 - val_mae: 50375.7148
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49974.3281 - mae: 49974.3281 - val_loss: 50365.1797 - val_mae: 50365.1797
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50195.0352 - mae: 50195.0352 - val_loss: 50351.3477 - val_mae: 50351.3477
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49890.9922 - mae: 49890.9922 - val_loss: 50340.9219 - val_mae: 50340.9219
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49517.6562 - mae: 49517.6562 - val_loss: 50336.5742 - val_mae: 50336.5742
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49613.9023 - mae: 49613.9023 - val_loss: 50328.6719 - val_mae: 50328.6719
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50727.8750 - mae: 50727.8750 - val_loss: 50320.8164 - val_mae: 50320.8164
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49596.1641 - mae: 49596.1641 - val_loss: 50326.7461 - val_mae: 50326.7461
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50128.6953 - mae: 50128.6953 - val_loss: 50308.7266 - val_mae: 50308.7266
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49811.7344 - mae: 49811.7344 - val_loss: 50306.6367 - val_mae: 50306.6367
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49215.5117 - mae: 49215.5117 - val_loss: 50307.5430 - val_mae: 50307.5430
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49608.6367 - mae: 49608.6367 - val_loss: 50303.1484 - val_mae: 50303.1484
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49219.8047 - mae: 49219.8047 - val_loss: 50307.1562 - val_mae: 50307.1562
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 48782.4531 - mae: 48782.4531 - val_loss: 50288.8398 - val_mae: 50288.8398
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49611.0625 - mae: 49611.0625 - val_loss: 50288.4453 - val_mae: 50288.4453
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49740.0781 - mae: 49740.0781 - val_loss: 50287.0508 - val_mae: 50287.0508
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49898.3555 - mae: 49898.3555 - val_loss: 50286.9141 - val_mae: 50286.9141
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49221.2812 - mae: 49221.2812 - val_loss: 50289.3125 - val_mae: 50289.3125
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50390.4570 - mae: 50390.4570 - val_loss: 50291.0039 - val_mae: 50291.0039
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49874.6406 - mae: 49874.6406 - val_loss: 50288.6562 - val_mae: 50288.6562
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50125.1289 - mae: 50125.1289 - val_loss: 50283.0352 - val_mae: 50283.0352
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49564.7422 - mae: 49564.7422 - val_loss: 50279.3242 - val_mae: 50279.3242
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49925.0469 - mae: 49925.0469 - val_loss: 50275.7812 - val_mae: 50275.7812
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49303.0273 - mae: 49303.0273 - val_loss: 50276.8320 - val_mae: 50276.8320
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49343.3359 - mae: 49343.3359 - val_loss: 50282.4648 - val_mae: 50282.4648
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49762.2539 - mae: 49762.2539 - val_loss: 50279.9570 - val_mae: 50279.9570
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49164.8477 - mae: 49164.8477 - val_loss: 50283.4453 - val_mae: 50283.4453
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49356.5039 - mae: 49356.5039 - val_loss: 50284.1523 - val_mae: 50284.1523
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49204.9531 - mae: 49204.9531 - val_loss: 50277.0195 - val_mae: 50277.0195
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48832.2070 - mae: 48832.2070 - val_loss: 50275.4141 - val_mae: 50275.4141
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49300.1133 - mae: 49300.1133 - val_loss: 50285.8789 - val_mae: 50285.8789
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 48872.7578 - mae: 48872.7578 - val_loss: 50280.4805 - val_mae: 50280.4805
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49569.3438 - mae: 49569.3438 - val_loss: 50278.6172 - val_mae: 50278.6172
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49235.2109 - mae: 49235.2109 - val_loss: 50288.3789 - val_mae: 50288.3789
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49263.6641 - mae: 49263.6641 - val_loss: 50280.2812 - val_mae: 50280.2812
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49706.8281 - mae: 49706.8281 - val_loss: 50295.9531 - val_mae: 50295.9531
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49139.3008 - mae: 49139.3008 - val_loss: 50291.7734 - val_mae: 50291.7734
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49054.6484 - mae: 49054.6484 - val_loss: 50294.5586 - val_mae: 50294.5586
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49887.6641 - mae: 49887.6641 - val_loss: 50299.4883 - val_mae: 50299.4883
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49293.0781 - mae: 49293.0781 - val_loss: 50298.3711 - val_mae: 50298.3711

In [18]:
%load_ext tensorboard

In [19]:
%tensorboard --logdir regressionlogs/fit